version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: home-agent-redis
    ports:
      - "6379:6379"
    networks:
      - home-agent-network

  celery_worker:
    build:
      context: ./backend
    container_name: home-agent-celery
    command: celery -A app.api.v2.routes.agent worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - home-agent-network

  flower:
    build:
      context: ./backend
    container_name: home-agent-flower
    command: celery -A app.api.v2.routes.agent flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - home-agent-network

  backend:
    build: 
      context: ./backend
    container_name: home-agent-backend
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    ports: 
      - "5172:5172"
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 5172  --reload"
    depends_on:
      - redis
    networks: 
      - home-agent-network
  
networks:
  home-agent-network:
    driver: bridge